----------------------------------------------------------------------------------------------------
[ERROR] - 2021-10-17 09:09:30,713

Source log file: /root/react-django/src/backend/item/views.py line: 48

Traceback (most recent call last):
  File "/root/react-django/src/backend/item/views.py", line 44, in put
    serializer.save()
  File "/usr/lib/python3.9/site-packages/rest_framework/serializers.py", line 200, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/lib/python3.9/site-packages/rest_framework/serializers.py", line 970, in update
    info = model_meta.get_field_info(instance)
  File "/usr/lib/python3.9/site-packages/rest_framework/utils/model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'QuerySet' object has no attribute '_meta'

----------------------------------------------------------------------------------------------------
[ERROR] - 2021-10-17 09:09:30,745

Source log file: /usr/lib/python3.9/site-packages/django/utils/log.py line: 224

Internal Server Error: /api/item/phone/
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
----------------------------------------------------------------------------------------------------
[ERROR] - 2021-10-17 09:09:30,746

Source log file: /usr/lib/python3.9/site-packages/django/core/servers/basehttp.py line: 161

"PUT /api/item/phone/ HTTP/1.0" 500 69998
